# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build
FROM node:22-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json for dependencies installation
COPY package.json package-lock.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Production Image
FROM node:22-alpine AS release

# Set the working directory
WORKDIR /app

# Copy the build artifacts and necessary files from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Set environment variables
ENV NODE_ENV=production

# Install production dependencies
RUN npm ci --ignore-scripts --omit=dev

# Expose the necessary port
EXPOSE 3456

# Command to run the application
ENTRYPOINT ["node", "build/index.js"]
